CREATE TABLE user (
    id INT auto_increment NOT NULL,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT pk_id PRIMARY KEY (id)
